import Head from 'next/head'
import Carousel from 'react-multi-carousel';
import thendraConfig from 'thendra.config';
import swr from '../hooks/swr';
import Button from "../components/Global/Button"
import Image from "next/image";
import javas from "../img/javas.png"
import react from "../img/react.png"
import next from "../img/next.png"
import node from "../img/nodejs.png"
import html from "../img/html.png"
import css from "../img/css.png"
import php from "../img/php.png"
import csharp from "../img/csharp.png"
import cpp from "../img/cpp.png"
import python from "../img/py.png"
import mdb from "../img/mongo.png"



export default function Home() {

  const { data: _repositories } = swr('/api/repos');
  const repositories = _repositories ? _repositories : null;

  return (
    <>
      <Head>
        <title>Thendra | Full-stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <section id="about"><center>
          <h2 id='abouth2' main className='mt-[150px] text-5xl flex flex-col m-auto'>Hi there <br/>
          <h2 className='mr-[280px] m-auto flex'>I&apos;m </h2></h2>
          <span id='thendraa' className='text-5xl flex mt-[-65px] text-primary ml-[890px]'>Thendra</span>
          <p id='hakkımda' className='mt-7 font-bold'>Hi, I&apos;m Thendra. I am 17 years old. I am a 3rd year high school student. 
			I have been dealing with software for about 5 years. I started with node.js, 
			developed Discord Bot and made my biggest improvement with the latest FiveM script. 
			Software has been and continues to be my biggest hobby to date. 
			I&apos;m still improving myself.</p>

      <iframe src="https://linkcord.js.org/api/v3/widget/267373400022843393?type=spotify_large&theme=dark&background=060606&language=en" width="400" height="130" allowtransparency="true" frameborder="0"/></center>
        </section>

        <section id="achievements">
        <div className="h-[6rem] flex flex-col justify-center items-center mb-72">
        <div className="w-full lg:w-auto grid grid-cols-1 lg:grid-cols-4 gap-4 mt-24">
        <div className="rounded-lg border-2 border-gray-500/10 border-dotted px-4 py-2 text-center">
          <span className="text-primary uppercase">Technologies</span>
          <p className="text-gray-500 dark:text-gray-300 font-semibold text-xl">11+</p>
        </div>
        <div className="rounded-lg border-2 border-gray-500/10 border-dotted px-4 py-2 text-center">
          <span className="text-primary uppercase">Years of Experience</span>
          <p className="text-gray-500 dark:text-gray-300 font-semibold text-xl">5+</p>
        </div>
        <div className="rounded-lg border-2 border-gray-500/10 border-dotted px-4 py-2 text-center">
          <span className="text-primary uppercase">Completed Projects</span>
          <p className="text-gray-500 dark:text-gray-300 font-semibold text-xl">60+</p>
        </div>
        <div className="rounded-lg border-2 border-gray-500/10 border-dotted px-4 py-2 text-center">
          <span className="text-primary uppercase">Repositories</span>
          <p className="text-gray-500 dark:text-gray-300 font-semibold text-xl">24+</p>
        </div>
        </div>
        </div>
        </section>

        <section id="projects">
        <div className="mx-auto max-w-7xl my-24">
          <h1 className="font-display text-5xl font-medium sm:text-7xl text-black dark:text-white">My <span className="relative whitespace-nowrap text-primary"><svg aria-hidden="true" viewBox="0 0 418 42" className="absolute -mt-1 ml-1 top-3/5 left-0 h-[0.45em] w-full fill-primary/20 rotate-180" preserveAspectRatio="none"><path d="M203.371.916c-26.013-2.078-76.686 1.963-124.73 9.946L67.3 12.749C35.421 18.062 18.2 21.766 6.004 25.934 1.244 27.561.828 27.778.874 28.61c.07 1.214.828 1.121 9.595-1.176 9.072-2.377 17.15-3.92 39.246-7.496C123.565 7.986 157.869 4.492 195.942 5.046c7.461.108 19.25 1.696 19.17 2.582-.107 1.183-7.874 4.31-25.75 10.366-21.992 7.45-35.43 12.534-36.701 13.884-2.173 2.308-.202 4.407 4.442 4.734 2.654.187 3.263.157 15.593-.78 35.401-2.686 57.944-3.488 88.365-3.143 46.327.526 75.721 2.23 130.788 7.584 19.787 1.924 20.814 1.98 24.557 1.332l.066-.011c1.201-.203 1.53-1.825.399-2.335-2.911-1.31-4.893-1.604-22.048-3.261-57.509-5.556-87.871-7.36-132.059-7.842-23.239-.254-33.617-.116-50.627.674-11.629.54-42.371 2.494-46.696 2.967-2.359.259 8.133-3.625 26.504-9.81 23.239-7.825 27.934-10.149 28.304-14.005.417-4.348-3.529-6-16.878-7.066Z" /></svg><span className="relative">repositories</span></span></h1>
          <div id="repos" className="relative mt-16">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 mt-3">
                {_repositories ? (
                    repositories ? (
                        repositories.sort((a, b) => b.stargazers_count - a.stargazers_count).map((_, __) => (
                            <a key={__} target="_blank" rel="noreferrer" className="bg-zinc-400/5 hover:bg-zinc-400/10 active:opacity-50 transition-all duration-200 flex flex-col rounded-lg py-4 px-5 h-28 mt-4" href={`https://github.com/${_.full_name}`}>
                                <h1 className="leading-none text-lg font-medium text-white">{_.full_name}</h1>
                                <p className="font-display h-10 text-sm text-gray-500 font-light mt-1">{_.description}</p>
                                <div className="w-full mt-auto flex-1 flex items-end justify-end space-x-3">
                                  <div className="flex items-center">
                                    <i className="fal fa-code mr-2 w-5 text-green-400" />
                                    <p className="text-zinc-300">{_.language || "Plain/Text"}</p>
                                  </div>
                                    <h6 className="flex items-center gap-x-1 text-zinc-300 font-light">
                                        <i className="fa-regular fa-star text-orange-400 mr-1" /> {_.stargazers_count} Star
                                    </h6>
                                    <h6 className="flex items-center gap-x-1 text-zinc-300 font-light">
                                        <i className="fa-regular fa-code-merge text-sky-400 mr-1" /> {_.forks} Forks
                                    </h6>
                                </div>
                            </a>
                        ))
                    ) : (
                        <a target="_blank" rel="noreferrer" className="bg-zinc-400/5 hover:bg-zinc-400/10 active:opacity-50 transition-all duration-200 flex flex-col rounded-lg py-4 px-5 h-28" href="https://github.com/thendra-s">
                            <div className="animate-pulse h-6 w-40 rounded-lg bg-white/10" />
                            <div className="w-full mt-auto flex-1 flex items-end justify-end space-x-3">
                                <h6 className="flex items-center gap-x-1 text-zinc-300 font-light">
                                    <div className="animate-pulse h-6 w-20 rounded-lg bg-white/10" />
                                </h6>
                                <h6 className="flex items-center gap-x-1 text-zinc-300 font-light">
                                    <div className="animate-pulse h-6 w-20 rounded-lg bg-white/10" />
                                </h6>
                            </div>
                        </a>
                    )) :
                    <a target="_blank" rel="noreferrer" className="bg-zinc-400/5 hover:bg-zinc-400/10 active:opacity-50 transition-all duration-200 flex flex-col rounded-lg py-4 px-5 h-28" href="https://github.com/thendra-s">
                        <div className="animate-pulse h-6 w-40 rounded-lg bg-white/10" />
                        <div className="w-full mt-auto flex-1 flex items-end justify-end space-x-3">
                            <h6 className="flex items-center gap-x-1 text-zinc-300 font-light">
                                <div className="animate-pulse h-6 w-20 rounded-lg bg-white/10" />
                            </h6>
                            <h6 className="flex items-center gap-x-1 text-zinc-300 font-light">
                                <div className="animate-pulse h-6 w-20 rounded-lg bg-white/10" />
                            </h6>
                        </div>
                    </a>   
                }
                  
            </div>
          </div>
          </div><center>
          <a href={`https://github.com/${thendraConfig.githubName}`} target="_blank" rel="noreferrer">
                    <Button className="mt-6 mb-12 flex items-center gap-2 ml-[1030px]">
                    <i className="fab fa-github" />
                      View all repositories
                    <i className="fal fa-arrow-right -rotate-45 text-xs" />
                    </Button>
                  </a></center>
          </section><br/>

        <section id="languages">
          <div className="mx-auto max-w-7xl my-24">
      <h1 className="font-display text-5xl font-medium sm:text-7xl text-black dark:text-white text-right">Technologies <span className="relative whitespace-nowrap text-primary"><svg aria-hidden="true" viewBox="0 0 418 42" className="absolute -mt-1 ml-1 top-3/5 left-0 h-[0.45em] w-full fill-primary/20 rotate-180" preserveAspectRatio="none"><path d="M203.371.916c-26.013-2.078-76.686 1.963-124.73 9.946L67.3 12.749C35.421 18.062 18.2 21.766 6.004 25.934 1.244 27.561.828 27.778.874 28.61c.07 1.214.828 1.121 9.595-1.176 9.072-2.377 17.15-3.92 39.246-7.496C123.565 7.986 157.869 4.492 195.942 5.046c7.461.108 19.25 1.696 19.17 2.582-.107 1.183-7.874 4.31-25.75 10.366-21.992 7.45-35.43 12.534-36.701 13.884-2.173 2.308-.202 4.407 4.442 4.734 2.654.187 3.263.157 15.593-.78 35.401-2.686 57.944-3.488 88.365-3.143 46.327.526 75.721 2.23 130.788 7.584 19.787 1.924 20.814 1.98 24.557 1.332l.066-.011c1.201-.203 1.53-1.825.399-2.335-2.911-1.31-4.893-1.604-22.048-3.261-57.509-5.556-87.871-7.36-132.059-7.842-23.239-.254-33.617-.116-50.627.674-11.629.54-42.371 2.494-46.696 2.967-2.359.259 8.133-3.625 26.504-9.81 23.239-7.825 27.934-10.149 28.304-14.005.417-4.348-3.529-6-16.878-7.066Z" /></svg><span className="relative">I use</span></span></h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mt-12">
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={react} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="React" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">React</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={next} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="Next.js" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">Next.js</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={node} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="Node.js" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">Node.js</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
            <Image src={javas} width="32" height="32" className="bg-white/5 p-1 w-[32px] h-[32px] rounded-md" alt="Javascript" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">Javascript</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={html} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="HTML" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">HTML</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={css} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="CSS" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">CSS</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={php} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="PHP" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">PHP</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={csharp} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="C#" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">C#</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={cpp} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="C++" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">C++</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl  border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={python} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="Python" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">Python</h2>
            </div>
          </div>
          <div className="group flex justify-between items-center relative bg-gray-600/5 dark:shadow-2xl border border-gray-500/25 hover:border-primary hover:shadow-xl rounded-lg overflow-hidden p-2.5 transition-all duration-200">
          <Image src={mdb} width="32" height="32" className="bg-transparent/5 p-1 w-[32px] h-[32px] rounded-md" alt="MongoDB" />
            <div className="relative">
              <h2 className="font-display text-xl font-medium text-black dark:text-white">MongoDB</h2>
            </div>
          </div>
      </div>
    </div>
    </section>
      </main>
    </>
  )
}